import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";
import UserDetailsProvider from "./context/UserDetailsProvider";
import SearchProvider from "./context/SearchProvider";
import ReduxProvider from "./components/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Provider store={store}> */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <SessionWrapper>
            <UserDetailsProvider>
              <SearchProvider>{children}</SearchProvider>
            </UserDetailsProvider>
          </SessionWrapper>
        </ReduxProvider>
      </body>
      {/* </Provider> */}
    </html>
  );
}
