import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper";
import UserDetailsProvider from "./context/UserDetailsProvider";
import SearchProvider from "./context/SearchProvider";
import ReduxProvider from "./components/ReduxProvider";
import SellerNotificationProvider from "./context/SellerNotificationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GreatMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <SessionWrapper>
            <SellerNotificationProvider>
              <UserDetailsProvider>
                <SearchProvider>{children}</SearchProvider>
              </UserDetailsProvider>
            </SellerNotificationProvider>
          </SessionWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
